//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int id { get; set; }
        public string description { get; set; }
        public string amenities { get; set; }
        public string roomdetails { get; set; }
        public string hotelname { get; set; }
        public string location { get; set; }
        public string imagenm { get; set; }
        public string address { get; set; }
    }
}
